name: Build and Test

on:
  push:
    branches: [ main ]  # Run on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machine

    steps:
    - uses: actions/checkout@v3  # Checkout code from the repository

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install
